language: python
python:
  - "3.7-dev"
cache: pip
before_script:
  - wget https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz
  - tar -xzvf GeoLite2-City.tar.gz  --strip-components 1
  - mv *.mmdb ./geo.mmdb
script:
  - make test
